import { Puzzle } from '../puzzle-service';

export const CodeCrackerPuzzles: Puzzle[] = [
  {
    id: 'code_001',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Number code: A=1, B=2, C=3...\nDecode: 3-1-20',
    options: ['CAT', 'DOG', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'C=3, A=1, T=20. So 3-1-20 spells CAT.',
  },
  {
    id: 'code_002',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Reverse the letters:\nDOG → ?',
    options: ['GOD', 'DOG', 'OGD', 'GDO'],
    correctAnswer: 0,
    explanation: 'Reversing DOG letter by letter gives GOD.',
  },
  {
    id: 'code_003',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Shift each letter forward by 1:\nA→B, B→C, C→?\nDecode: ABC',
    options: ['BCD', 'ABC', 'CDE', 'DEF'],
    correctAnswer: 0,
    explanation: 'Shifting each letter forward by 1: A→B, B→C, C→D. ABC becomes BCD.',
  },
  {
    id: 'code_004',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Number code: A=1, B=2, C=3...\nDecode: 4-15-7',
    options: ['DOG', 'CAT', 'FOX', 'BAT'],
    correctAnswer: 0,
    explanation: 'D=4, O=15, G=7. So 4-15-7 spells DOG.',
  },
  {
    id: 'code_005',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'First and last letter swap:\nBOOK → ?',
    options: ['KOOB', 'BOOK', 'OOBK', 'KBOO'],
    correctAnswer: 0,
    explanation: 'Swap B (first) with K (last): BOOK → KOOB.',
  },
  {
    id: 'code_006',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Remove vowels (A,E,I,O,U):\nHELLO → ?',
    options: ['HLL', 'HELL', 'ELO', 'HEL'],
    correctAnswer: 0,
    explanation: 'Removing vowels E and O from HELLO leaves HLL.',
  },
  {
    id: 'code_007',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Shift forward by 1:\nSUN → ?',
    options: ['TVO', 'SUN', 'RUM', 'TUN'],
    correctAnswer: 0,
    explanation: 'S→T, U→V, N→O. SUN becomes TVO.',
  },
  {
    id: 'code_008',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Number code: A=1, B=2, C=3...\nDecode: 2-1-20',
    options: ['BAT', 'CAT', 'RAT', 'HAT'],
    correctAnswer: 0,
    explanation: 'B=2, A=1, T=20. So 2-1-20 spells BAT.',
  },
  {
    id: 'code_009',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Reverse the word:\nSTAR → ?',
    options: ['RATS', 'TARS', 'ARTS', 'STRA'],
    correctAnswer: 0,
    explanation: 'Reversing STAR gives RATS.',
  },
  {
    id: 'code_010',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Replace each letter with the next one:\nZ → A, Y → Z\nDecode: XYZ',
    options: ['YZA', 'XYZ', 'ZAB', 'ABC'],
    correctAnswer: 0,
    explanation: 'X→Y, Y→Z, Z→A. XYZ becomes YZA.',
  },
  {
    id: 'code_011',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Number code: A=1, B=2, C=3...\nDecode: 18-1-20',
    options: ['RAT', 'BAT', 'CAT', 'HAT'],
    correctAnswer: 0,
    explanation: 'R=18, A=1, T=20. So 18-1-20 spells RAT.',
  },
  {
    id: 'code_012',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Shift backward by 1:\nB→A, C→B, D→?\nDecode: DOG',
    options: ['CNF', 'DOG', 'EPH', 'BOE'],
    correctAnswer: 0,
    explanation: 'D→C, O→N, G→F. DOG becomes CNF.',
  },
  {
    id: 'code_013',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Swap first and last:\nCAR → ?',
    options: ['RAC', 'CAR', 'ACR', 'RCA'],
    correctAnswer: 0,
    explanation: 'Swap C (first) with R (last): CAR → RAC.',
  },
  {
    id: 'code_014',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Number code: A=1, B=2, C=3...\nDecode: 16-9-7',
    options: ['PIG', 'DOG', 'CAT', 'FOX'],
    correctAnswer: 0,
    explanation: 'P=16, I=9, G=7. So 16-9-7 spells PIG.',
  },
  {
    id: 'code_015',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'easy',
    question: 'Reverse it:\nTOP → ?',
    options: ['POT', 'TOP', 'OPT', 'TPO'],
    correctAnswer: 0,
    explanation: 'Reversing TOP gives POT.',
  },
  {
    id: 'code_016',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Caesar Cipher (shift +3):\nA→D, B→E, C→F\nDecode: FDW',
    options: ['CAT', 'DOG', 'BAT', 'FAT'],
    correctAnswer: 0,
    explanation: 'Shift back by 3: F→C, D→A, W→T. FDW decodes to CAT.',
  },
  {
    id: 'code_017',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Reverse alphabet: A=Z, B=Y, C=X...\nDecode: XZG',
    options: ['CAT', 'DOG', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'X=C (26-24=2+1=3rd letter), Z=A (26th→1st), G=T (26-6=20th). XZG = CAT.',
  },
  {
    id: 'code_018',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Vowel swap: A↔E, I↔O\nDecode: CET',
    options: ['CAT', 'CUT', 'COT', 'CIT'],
    correctAnswer: 0,
    explanation: 'E swaps to A: CET → CAT.',
  },
  {
    id: 'code_019',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Number pattern: A=26, B=25, C=24 (reverse)\nDecode: 26-18-20',
    options: ['ART', 'CAT', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'A=26, R=18 (26-8=18), T=20 (26-6=20). So 26-18-20 = ART.',
  },
  {
    id: 'code_020',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Caesar shift +5:\nDecode: HFYX',
    options: ['CATS', 'DOGS', 'BIRD', 'FISH'],
    correctAnswer: 0,
    explanation: 'Shift back 5: H→C, F→A, Y→T, X→S. HFYX = CATS.',
  },
  {
    id: 'code_021',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Mirror pairs: A↔Z, B↔Y, C↔X, D↔W...\nDecode: WLT',
    options: ['DOG', 'CAT', 'FOX', 'BAT'],
    correctAnswer: 0,
    explanation: 'W=D (23rd↔4th), L=O (12th↔15th), T=G (20th↔7th). WLT = DOG.',
  },
  {
    id: 'code_022',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Caesar shift +2:\nDecode: EQQN',
    options: ['BOOK', 'COOL', 'DOOR', 'MOON'],
    correctAnswer: 1,
    explanation: 'Shift back 2: E-2=C, Q-2=O, Q-2=O, N-2=L. EQQN = COOL.',
  },
  {
    id: 'code_023',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Every 2nd letter: HXEXLXLXOX → Remove X\nDecode result:',
    options: ['HELLO', 'WORLD', 'HELP', 'HELL'],
    correctAnswer: 0,
    explanation: 'Remove all X: HXEXLXLXOX → HELLO.',
  },
  {
    id: 'code_024',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'First and last swap:\nDecode: TAEB',
    options: ['BEAT', 'BETA', 'BATE', 'ABLE'],
    correctAnswer: 0,
    explanation: 'Swap first (T) and last (B): TAEB → BEAT.',
  },
  {
    id: 'code_025',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Caesar shift +4:\nDecode: GYX',
    options: ['CUP', 'CUB', 'CUT', 'CAT'],
    correctAnswer: 2,
    explanation: 'Shift back 4: G(7)-4=C(3), Y(25)-4=U(21), X(24)-4=T(20). GYX = CUT.',
  },
  {
    id: 'code_026',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'ROT13 (shift by 13):\nA→N, B→O, M→Z, N→A\nDecode: PNGPU',
    options: ['CATCH', 'MATCH', 'PATCH', 'WATCH'],
    correctAnswer: 0,
    explanation: 'Shift by 13: P→C, N→A, G→T, P→C, U→H. PNGPU = CATCH.',
  },
  {
    id: 'code_027',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Number code with multiply: A=1, B=2...\nDecode: (2×5)-(1×1)-(4×5)',
    options: ['JAT', 'KAT', 'CAT', 'BAT'],
    correctAnswer: 0,
    explanation: '(2×5)=10=J, (1×1)=1=A, (4×5)=20=T. Result: JAT.',
  },
  {
    id: 'code_028',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Reverse vowels only:\nHOUSE → H-O-U-S-E → H-U-O-S-E\nDecode: RUOD',
    options: ['ROAD', 'READ', 'RUDE', 'RODE'],
    correctAnswer: 0,
    explanation: 'Vowels are O-A in ROAD. Reverse to A-O: RUOD → ROAD.',
  },
  {
    id: 'code_029',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Skip pattern: Every other letter from BXAXNXK → Remove X\nResult:',
    options: ['BANK', 'BANK', 'BUNK', 'BONK'],
    correctAnswer: 0,
    explanation: 'Remove X: BXAXNXK → BANK.',
  },
  {
    id: 'code_030',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'medium',
    question: 'Caesar +7:\nDecode: OVTL',
    options: ['HUMP', 'HOME', 'HOPE', 'HOLE'],
    correctAnswer: 1,
    explanation: 'Shift back 7: O→H, V→O, T→M, L→E. OVTL = HOME.',
  },
  {
    id: 'code_031',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Atbash cipher (A↔Z, B↔Y, C↔X, D↔W...):\nDecode: XZGXS',
    options: ['CATCH', 'MATCH', 'BATCH', 'WATCH'],
    correctAnswer: 0,
    explanation: 'X=C, Z=A, G=T, X=C, S=H. XZGXS = CATCH.',
  },
  {
    id: 'code_032',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Binary code: 01001000 = H (72 in ASCII)\n01001001 = ?',
    options: ['G', 'H', 'I', 'J'],
    correctAnswer: 2,
    explanation: '01001001 = 73 in decimal, which is ASCII code for I.',
  },
  {
    id: 'code_033',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Caesar shift +7:\nDecode: OVWL',
    options: ['IDEA', 'HOPE', 'ITEM', 'JOKE'],
    correctAnswer: 1,
    explanation: 'Shift back 7: O-7=H, V-7=O, W-7=P, L-7=E. OVWL = HOPE.',
  },
  {
    id: 'code_034',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Number positions:\nA=1, B=2, C=3, D=4...\nDecode: 3-1-14',
    options: ['CAN', 'BAD', 'CAD', 'MAN'],
    correctAnswer: 0,
    explanation: 'C=3, A=1, N=14. Result: 3-1-14 = CAN.',
  },
  {
    id: 'code_035',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Keyboard shift (QWERTY): Each letter → right neighbor\nA→S, S→D, D→F\nDecode: VSY',
    options: ['CAT', 'DOG', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'Shift left: V→C, S→A, Y→T. VSY = CAT.',
  },
  {
    id: 'code_036',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Morse code: -.-. .- -\nDecode:',
    options: ['CAT', 'DOG', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'Morse: -.-. = C, .- = A, - = T. Result: CAT.',
  },
  {
    id: 'code_037',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Fibonacci shift: Position shifts by 1,1,2,3,5...\nB(+1)→C, A(+1)→B, T(+2)→V\nDecode: CBV',
    options: ['BAT', 'CAT', 'RAT', 'HAT'],
    correctAnswer: 0,
    explanation: 'Reverse: C(-1)=B, B(-1)=A, V(-2)=T. CBV = BAT.',
  },
  {
    id: 'code_038',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Letter position sum:\nC(3) + A(1) + T(20) = ?\nWhat is the sum?',
    options: ['24', '23', '25', '26'],
    correctAnswer: 0,
    explanation: 'C=3, A=1, T=20. Sum: 3+1+20 = 24.',
  },
  {
    id: 'code_039',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Reverse every pair of letters:\nDO|GS → OD|SG\nDecode: ODSG',
    options: ['DOGS', 'GODS', 'DIGS', 'DOSE'],
    correctAnswer: 0,
    explanation: 'Reverse each pair: OD→DO, SG→GS. ODSG = DOGS.',
  },
  {
    id: 'code_040',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Old phone keypad code:\n2=ABC, 8=TUV, 9=WXYZ\nDecode: 222-2-8',
    options: ['BAT', 'CAT', 'TAB', 'AAT'],
    correctAnswer: 1,
    explanation: 'On old phones: 222 (press 2 three times) = C, 2 (press once) = A, 8 (press once) = T. Result: CAT.',
  },
  {
    id: 'code_041',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Rail Fence (2 rails):\nCATS → C.T. / .A.S → CTAS\nDecode: CTAS',
    options: ['CATS', 'CAST', 'SCAT', 'ACTS'],
    correctAnswer: 0,
    explanation: 'Rail fence decode: CT (top) + AS (bottom) → C-A-T-S = CATS.',
  },
  {
    id: 'code_042',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Columnar transposition (key: 312):\nDOG → D(3)O(1)G(2) → ODG\nDecode: ODG',
    options: ['DOG', 'GOD', 'DGO', 'OGD'],
    correctAnswer: 0,
    explanation: 'Reorder by key 312: position 1←O, position 2←G, position 3←D. ODG → DOG.',
  },
  {
    id: 'code_043',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Letter sum code: A=1, B=2...\nWhich word has sum = 27?',
    options: ['CAT (24)', 'FAT (27)', 'BAT (23)', 'RAT (39)'],
    correctAnswer: 1,
    explanation: 'F=6, A=1, T=20. Sum: 6+1+20 = 27. FAT is correct.',
  },
  {
    id: 'code_044',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Increasing shift per letter:\n1st-1, 2nd-2, 3rd-3\nDecode: CCW',
    options: ['DOG', 'CAT', 'BAT', 'RAT'],
    correctAnswer: 2,
    explanation: 'C-1=B, C-2=A, W-3=T. CCW = BAT.',
  },
  {
    id: 'code_045',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Remove all X letters:\nDecode: BXAXTX',
    options: ['BAT', 'XAX', 'BTX', 'AXT'],
    correctAnswer: 0,
    explanation: 'Remove X letters: BXAXTX → BAT.',
  },
  {
    id: 'code_046',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'ROT13 cipher (shift by 13):\nDecode: PURPX',
    options: ['CHECK', 'PURPX', 'CRACK', 'CHESS'],
    correctAnswer: 0,
    explanation: 'ROT13: P→C, U→H, R→E, P→C, X→K. PURPX = CHECK.',
  },
  {
    id: 'code_047',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Alphanumeric: Replace numbers with letters\n3-1-20 using position\nDecode: 3-1-20',
    options: ['CAT', 'DOG', 'BAT', 'RAT'],
    correctAnswer: 0,
    explanation: 'C=3, A=1, T=20. Result: CAT.',
  },
  {
    id: 'code_048',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Caesar shift -6:\nDecode: HGZ',
    options: ['CAT', 'BAT', 'RAT', 'FAT'],
    correctAnswer: 1,
    explanation: 'Shift back 6: H-6=B, G-6=A, Z-6=T. HGZ = BAT.',
  },
  {
    id: 'code_049',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Bacon cipher (simplified): Each letter = 5-bit binary\nA=00000, B=00001, C=00010\nDecode: 00010-00000-10011',
    options: ['CAT', 'BAT', 'DOG', 'RAT'],
    correctAnswer: 0,
    explanation: '00010=C(3), 00000=A(1), 10011=T(20). Result: CAT.',
  },
  {
    id: 'code_050',
    type: 'Code Cracker',
    icon: '🔐',
    difficulty: 'hard',
    question: 'Atbash cipher: A↔Z, B↔Y, C↔X...\nDecode: DLLW',
    options: ['DOOR', 'WOOD', 'BOOK', 'FOOD'],
    correctAnswer: 1,
    explanation: 'Atbash reverses alphabet: D(4)↔W(23), L(12)↔O(15), L↔O, W↔D. DLLW = WOOD.',
  },
];
