import { Puzzle } from "../puzzle-service";

export const LogicPuzzles: Puzzle[] = [
  {
    id: 'logic_001',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If all roses are flowers and some flowers fade quickly, can we conclude that some roses fade quickly?',
    options: ['Yes', 'No', 'Maybe', 'Cannot determine'],
    correctAnswer: 3,
    explanation: 'We cannot determine this because we don\'t know which specific flowers fade quickly.',
  },
  {
    id: 'logic_002',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'A farmer has 17 sheep. All but 9 die. How many are left?',
    options: ['8', '9', '17', '0'],
    correctAnswer: 1,
    explanation: '"All but 9" means 9 sheep survived.',
  },
  {
    id: 'logic_003',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If you have 3 apples and take away 2, how many do you have?',
    options: ['1', '2', '3', '5'],
    correctAnswer: 1,
    explanation: 'You took 2 apples, so you have 2 apples.',
  },
  {
    id: 'logic_004',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next in this sequence? 2, 4, 6, 8, __',
    options: ['9', '10', '12', '14'],
    correctAnswer: 1,
    explanation: 'The pattern adds 2 each time: 2+2=4, 4+2=6, 6+2=8, 8+2=10',
  },
  {
    id: 'logic_005',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If today is Monday, what day was it 3 days ago?',
    options: ['Thursday', 'Friday', 'Saturday', 'Sunday'],
    correctAnswer: 1,
    explanation: 'Going back 3 days from Monday: Sunday, Saturday, Friday.',
  },
  {
    id: 'logic_006',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Tom is taller than Sam. Sam is taller than Mike. Who is the shortest?',
    options: ['Tom', 'Sam', 'Mike', 'Cannot tell'],
    correctAnswer: 2,
    explanation: 'Mike is shorter than Sam, who is shorter than Tom, making Mike the shortest.',
  },
  {
    id: 'logic_007',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'What comes next? 1, 1, 2, 3, 5, 8, __',
    options: ['11', '13', '15', '16'],
    correctAnswer: 1,
    explanation: 'Fibonacci sequence: each number is the sum of the previous two (5+8=13).',
  },
  {
    id: 'logic_008',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'If it takes 5 machines 5 minutes to make 5 widgets, how long would it take 100 machines to make 100 widgets?',
    options: ['5 minutes', '20 minutes', '100 minutes', '500 minutes'],
    correctAnswer: 0,
    explanation: 'Each machine makes 1 widget in 5 minutes, regardless of how many machines there are.',
  },
  {
    id: 'logic_009',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A bat and ball cost $1.10. The bat costs $1 more than the ball. How much does the ball cost?',
    options: ['$0.10', '$0.05', '$0.15', '$0.55'],
    correctAnswer: 1,
    explanation: 'Ball = $0.05, Bat = $1.05. The bat costs $1 more than the ball, and together they equal $1.10.',
  },
  {
    id: 'logic_010',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'In a race, you overtake the person in 2nd place. What position are you in now?',
    options: ['1st', '2nd', '3rd', '4th'],
    correctAnswer: 1,
    explanation: 'If you overtake the person in 2nd place, you take their position and become 2nd.',
  },
  {
    id: 'logic_011',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Three light switches outside a room control three bulbs inside. You can only enter the room once. How can you determine which switch controls which bulb?',
    options: ['Turn on two switches', 'Turn on one, leave one off', 'Turn one on for 5 min, then off', 'Impossible'],
    correctAnswer: 2,
    explanation: 'Turn on switch 1 for 5 minutes, then off. Turn on switch 2. The hot bulb is switch 1, the lit bulb is switch 2, the cold/off bulb is switch 3.',
  },
  {
    id: 'logic_012',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'You have 8 balls, one is heavier. Using a balance scale only twice, can you find the heavy ball?',
    options: ['Yes', 'No', 'Need 3 weighings', 'Need 4 weighings'],
    correctAnswer: 0,
    explanation: 'Divide into groups of 3, 3, and 2. First weighing identifies which group. Second weighing finds the exact ball.',
  },
  {
    id: 'logic_013',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What is always coming but never arrives?',
    options: ['Yesterday', 'Tomorrow', 'Today', 'The past'],
    correctAnswer: 1,
    explanation: 'Tomorrow is always one day away, so it never actually arrives.',
  },
  {
    id: 'logic_014',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? A, C, E, G, __',
    options: ['H', 'I', 'J', 'K'],
    correctAnswer: 1,
    explanation: 'Skip one letter each time: A(skip B)C(skip D)E(skip F)G(skip H)I',
  },
  {
    id: 'logic_015',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If 2 cats can catch 2 mice in 2 minutes, how many cats are needed to catch 100 mice in 100 minutes?',
    options: ['2 cats', '50 cats', '100 cats', '200 cats'],
    correctAnswer: 0,
    explanation: 'Each cat catches one mouse per 2 minutes, so 2 cats catch 100 mice in 100 minutes.',
  },
  {
    id: 'logic_016',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A book has 500 pages. How many times does the digit 1 appear in the page numbers?',
    options: ['100', '150', '200', '250'],
    correctAnswer: 2,
    explanation: 'Count 1s in ones, tens, and hundreds places: 100 (1-100) + 100 (101-199, 201-299, etc.) = 200.',
  },
  {
    id: 'logic_017',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Which word does not belong? Dog, Cat, Bird, Chair',
    options: ['Dog', 'Cat', 'Bird', 'Chair'],
    correctAnswer: 3,
    explanation: 'Chair is not a living animal.',
  },
  {
    id: 'logic_018',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'If you have a 7-liter jug and a 4-liter jug, how can you measure exactly 6 liters?',
    options: ['Fill 7L twice', 'Fill 4L once, 7L once', 'Fill 7L, pour to 4L, repeat', 'Impossible'],
    correctAnswer: 2,
    explanation: 'Fill 7L, pour 4L out (3L remains). Pour those 3L to 4L jug, fill 7L again, top off the 4L (6L remains in 7L jug).',
  },
  {
    id: 'logic_019',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What is the next number? 10, 20, 30, 40, __',
    options: ['45', '50', '60', '100'],
    correctAnswer: 1,
    explanation: 'Add 10 each time: 10+10=20, 20+10=30, 30+10=40, 40+10=50',
  },
  {
    id: 'logic_020',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If all bloops are razzies and all razzies are lazzies, then all bloops are definitely lazzies?',
    options: ['True', 'False', 'Maybe', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'This is a valid syllogism: if A⊂B and B⊂C, then A⊂C.',
  },
  {
    id: 'logic_021',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A clock shows 3:15. What is the angle between the hour and minute hands?',
    options: ['0°', '7.5°', '15°', '22.5°'],
    correctAnswer: 1,
    explanation: 'At 3:15, the minute hand is at 90° and the hour hand is at 97.5° (15min × 0.5°/min past 90°). Difference = 7.5°.',
  },
  {
    id: 'logic_022',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What weighs more: a pound of feathers or a pound of bricks?',
    options: ['Feathers', 'Bricks', 'Same weight', 'Cannot tell'],
    correctAnswer: 2,
    explanation: 'A pound is a pound, regardless of what it\'s made of.',
  },
  {
    id: 'logic_023',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Five friends finish a race. Amy finished before Ben but after Charlie. Dan finished before Emma but after Ben. Who won?',
    options: ['Amy', 'Ben', 'Charlie', 'Dan'],
    correctAnswer: 2,
    explanation: 'Order: Charlie, Amy, Ben, Dan, Emma. Charlie won.',
  },
  {
    id: 'logic_024',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'You have 12 coins, one is fake (lighter). Using a balance scale 3 times, can you identify it?',
    options: ['Yes', 'No', 'Need 4 weighings', 'Only with luck'],
    correctAnswer: 0,
    explanation: 'Divide into groups of 4. Each weighing eliminates 2/3 of remaining coins. 12→4→between 2→1 coin.',
  },
  {
    id: 'logic_025',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? Circle, Square, Triangle, Circle, Square, __',
    options: ['Circle', 'Square', 'Triangle', 'Pentagon'],
    correctAnswer: 2,
    explanation: 'The pattern repeats: Circle, Square, Triangle.',
  },
  {
    id: 'logic_026',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A snail climbs a 10-meter wall. Each day it climbs 3 meters, each night it slides 2 meters. How many days to reach the top?',
    options: ['7 days', '8 days', '10 days', '15 days'],
    correctAnswer: 1,
    explanation: 'After 7 days: 7m (net 1m/day × 7). On day 8, it climbs 3m to reach 10m before sliding.',
  },
  {
    id: 'logic_027',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Three people check into a hotel room that costs $30. They each pay $10. Later, the manager realizes it\'s $25 and gives the bellboy $5 to return. He keeps $2 and gives them each $1 back. They paid $9 each ($27) + bellboy\'s $2 = $29. Where\'s the missing $1?',
    options: ['With the manager', 'With bellboy', 'No missing dollar', 'With the guests'],
    correctAnswer: 2,
    explanation: 'Trick question! They paid $27 ($25 to hotel + $2 to bellboy). The $27 already includes the bellboy\'s $2.',
  },
  {
    id: 'logic_028',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What is the next number? 3, 6, 9, 12, __',
    options: ['13', '14', '15', '16'],
    correctAnswer: 2,
    explanation: 'Add 3 each time: 3+3=6, 6+3=9, 9+3=12, 12+3=15',
  },
  {
    id: 'logic_029',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Mary\'s father has 5 daughters: Nana, Nene, Nini, Nono. What is the 5th daughter\'s name?',
    options: ['Nunu', 'Mary', 'Nana', 'Cannot tell'],
    correctAnswer: 1,
    explanation: 'The question states "Mary\'s father" so Mary is the 5th daughter.',
  },
  {
    id: 'logic_030',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Two trains are 100km apart, heading toward each other at 50km/h each. A bird flies between them at 75km/h. How far does the bird fly before the trains meet?',
    options: ['50km', '75km', '100km', '150km'],
    correctAnswer: 1,
    explanation: 'Trains meet in 1 hour (100km ÷ 100km/h combined). Bird flies at 75km/h for 1 hour = 75km.',
  },
  {
    id: 'logic_031',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'If you overtake the last person in a race, what position are you in?',
    options: ['Last', '2nd to last', 'Middle', 'Impossible'],
    correctAnswer: 3,
    explanation: 'You cannot overtake the last person - they are already last!',
  },
  {
    id: 'logic_032',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A doctor gives you 3 pills and tells you to take one every 30 minutes. How long before you run out?',
    options: ['30 minutes', '1 hour', '1.5 hours', '90 minutes'],
    correctAnswer: 1,
    explanation: 'Take 1st pill now, 2nd after 30 min, 3rd after another 30 min. Total: 1 hour.',
  },
  {
    id: 'logic_033',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'You have two ropes that each take exactly 60 minutes to burn, but burn unevenly. How do you measure 45 minutes?',
    options: ['Burn 3/4 of one rope', 'Use a watch', 'Light both ends of one, one end of other', 'Impossible'],
    correctAnswer: 2,
    explanation: 'Light both ends of rope 1 (burns in 30min) and one end of rope 2. When rope 1 is done (30min), light other end of rope 2 (15min more). Total: 45min.',
  },
  {
    id: 'logic_034',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? 100, 95, 90, 85, __',
    options: ['75', '80', '85', '90'],
    correctAnswer: 1,
    explanation: 'Subtract 5 each time: 100-5=95, 95-5=90, 90-5=85, 85-5=80',
  },
  {
    id: 'logic_035',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A man builds a rectangular house with all 4 sides facing south. A bear walks by. What color is the bear?',
    options: ['Brown', 'Black', 'White', 'Cannot tell'],
    correctAnswer: 2,
    explanation: 'The house must be at the North Pole for all sides to face south. Only polar bears (white) live there.',
  },
  {
    id: 'logic_036',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'A woman had two sons born at the same hour of the same day of the same year, but they are not twins. How is this possible?',
    options: ['Adopted', 'Step-brothers', 'Triplets', 'Different mothers'],
    correctAnswer: 2,
    explanation: 'They were part of triplets (or higher multiples), so they\'re not twins but were born at the same time.',
  },
  {
    id: 'logic_037',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What is the odd one out? 2, 4, 6, 9, 10',
    options: ['2', '4', '9', '10'],
    correctAnswer: 2,
    explanation: '9 is the only odd number.',
  },
  {
    id: 'logic_038',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A man walks 1 mile south, 1 mile east, 1 mile north and ends where he started. Where is he?',
    options: ['North Pole', 'South Pole', 'Equator', 'Nowhere'],
    correctAnswer: 0,
    explanation: 'Only at the North Pole would this path return you to the start.',
  },
  {
    id: 'logic_039',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'You have 9 balls, all look identical. One is heavier. Using a balance scale twice, can you find the heavy one?',
    options: ['Yes', 'No', 'Need 3 tries', 'Only sometimes'],
    correctAnswer: 0,
    explanation: 'Divide into 3 groups of 3. First weighing finds heavy group. Second weighing finds exact ball.',
  },
  {
    id: 'logic_040',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? 1, 4, 9, 16, 25, __',
    options: ['30', '35', '36', '49'],
    correctAnswer: 2,
    explanation: 'Square numbers: 1², 2², 3², 4², 5², 6² = 36',
  },
  {
    id: 'logic_041',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'If 5 cats catch 5 rats in 5 minutes, how many cats catch 100 rats in 100 minutes?',
    options: ['5', '20', '100', '500'],
    correctAnswer: 0,
    explanation: 'Each cat catches 1 rat per 5 minutes. 5 cats catch 100 rats in 100 minutes (20 rats each).',
  },
  {
    id: 'logic_042',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Two fathers and two sons go fishing. They each catch a fish, yet only 3 fish are caught. How?',
    options: ['One lied', 'Shared a fish', 'Grandfather, father, son', 'Impossible'],
    correctAnswer: 2,
    explanation: 'There are only 3 people: grandfather (father), father (son and father), and son.',
  },
  {
    id: 'logic_043',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What is always in front of you but can\'t be seen?',
    options: ['Air', 'The future', 'Your nose', 'Light'],
    correctAnswer: 1,
    explanation: 'The future is always ahead of you but cannot be seen.',
  },
  {
    id: 'logic_044',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'A man lives on the 15th floor. Every day he takes the elevator down. Coming home, he takes it to the 10th floor and walks up 5. Why?',
    options: ['Exercise', 'Broken elevator', 'Too short to reach 15', 'Likes stairs'],
    correctAnswer: 2,
    explanation: 'He\'s too short to reach the button for the 15th floor, but can reach the 10th.',
  },
  {
    id: 'logic_045',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'A lily pad doubles in size daily. It takes 48 days to cover the pond. How long to cover half?',
    options: ['24 days', '40 days', '47 days', '46 days'],
    correctAnswer: 2,
    explanation: 'If it doubles daily and covers the pond on day 48, it covered half on day 47.',
  },
  {
    id: 'logic_046',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? Z, Y, X, W, __',
    options: ['V', 'U', 'T', 'A'],
    correctAnswer: 0,
    explanation: 'Alphabet in reverse: Z, Y, X, W, V',
  },
  {
    id: 'logic_047',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'If RED is coded as 27, BLUE as 31, what is GREEN?',
    options: ['40', '45', '50', '55'],
    correctAnswer: 2,
    explanation: 'Sum of letter positions: G(7)+R(18)+E(5)+E(5)+N(14) = 49, closest is 50.',
  },
  {
    id: 'logic_048',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'A boat has a ladder with 6 rungs. Rungs are 30cm apart. Bottom rung touches water. Tide rises 15cm/hour. How long until 3rd rung is underwater?',
    options: ['1 hour', '2 hours', '3 hours', 'Never'],
    correctAnswer: 3,
    explanation: 'The boat (and ladder) rises with the tide, so the same rung always touches the water.',
  },
  {
    id: 'logic_049',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'What comes next? 5, 10, 15, 20, __',
    options: ['22', '24', '25', '30'],
    correctAnswer: 2,
    explanation: 'Add 5 each time: 5+5=10, 10+5=15, 15+5=20, 20+5=25',
  },
  {
    id: 'logic_050',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Three people eat 3 pizzas in 3 hours. How long for 6 people to eat 6 pizzas?',
    options: ['3 hours', '6 hours', '9 hours', '1.5 hours'],
    correctAnswer: 0,
    explanation: 'Each person eats 1 pizza in 3 hours. With 6 people eating 6 pizzas (1 each), it still takes 3 hours.',
  }
];
