import { Puzzle } from "../puzzle-service";

export const LogicPuzzles: Puzzle[] = [
  {
    id: 'logic_001',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 1: If X is 1, and Y is 2, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 1 < 2, the answer is Yes.',
  },
  {
    id: 'logic_002',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 2: If X is 2, and Y is 3, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 2 < 3, the answer is Yes.',
  },
  {
    id: 'logic_003',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 3: If X is 3, and Y is 4, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 3 < 4, the answer is Yes.',
  },
  {
    id: 'logic_004',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 4: If X is 4, and Y is 5, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 4 < 5, the answer is Yes.',
  },
  {
    id: 'logic_005',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 5: If X is 5, and Y is 6, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 5 < 6, the answer is Yes.',
  },
  {
    id: 'logic_006',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 6: If X is 6, and Y is 7, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 6 < 7, the answer is Yes.',
  },
  {
    id: 'logic_007',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 7: If X is 7, and Y is 8, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 7 < 8, the answer is Yes.',
  },
  {
    id: 'logic_008',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 8: If X is 8, and Y is 9, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 8 < 9, the answer is Yes.',
  },
  {
    id: 'logic_009',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 9: If X is 9, and Y is 10, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 9 < 10, the answer is Yes.',
  },
  {
    id: 'logic_010',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 10: If X is 10, and Y is 11, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 10 < 11, the answer is Yes.',
  },
  {
    id: 'logic_011',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 11: If X is 11, and Y is 12, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 11 < 12, the answer is Yes.',
  },
  {
    id: 'logic_012',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 12: If X is 12, and Y is 13, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 12 < 13, the answer is Yes.',
  },
  {
    id: 'logic_013',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 13: If X is 13, and Y is 14, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 13 < 14, the answer is Yes.',
  },
  {
    id: 'logic_014',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 14: If X is 14, and Y is 15, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 14 < 15, the answer is Yes.',
  },
  {
    id: 'logic_015',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 15: If X is 15, and Y is 16, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 15 < 16, the answer is Yes.',
  },
  {
    id: 'logic_016',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 16: If X is 16, and Y is 17, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 16 < 17, the answer is Yes.',
  },
  {
    id: 'logic_017',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 17: If X is 17, and Y is 18, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 17 < 18, the answer is Yes.',
  },
  {
    id: 'logic_018',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 18: If X is 18, and Y is 19, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 18 < 19, the answer is Yes.',
  },
  {
    id: 'logic_019',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 19: If X is 19, and Y is 20, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 19 < 20, the answer is Yes.',
  },
  {
    id: 'logic_020',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 20: If X is 20, and Y is 21, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 20 < 21, the answer is Yes.',
  },
  {
    id: 'logic_021',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 21: If X is 21, and Y is 22, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 21 < 22, the answer is Yes.',
  },
  {
    id: 'logic_022',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 22: If X is 22, and Y is 23, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 22 < 23, the answer is Yes.',
  },
  {
    id: 'logic_023',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 23: If X is 23, and Y is 24, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 23 < 24, the answer is Yes.',
  },
  {
    id: 'logic_024',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 24: If X is 24, and Y is 25, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 24 < 25, the answer is Yes.',
  },
  {
    id: 'logic_025',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 25: If X is 25, and Y is 26, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 25 < 26, the answer is Yes.',
  },
  {
    id: 'logic_026',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 26: If X is 26, and Y is 27, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 26 < 27, the answer is Yes.',
  },
  {
    id: 'logic_027',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 27: If X is 27, and Y is 28, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 27 < 28, the answer is Yes.',
  },
  {
    id: 'logic_028',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 28: If X is 28, and Y is 29, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 28 < 29, the answer is Yes.',
  },
  {
    id: 'logic_029',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 29: If X is 29, and Y is 30, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 29 < 30, the answer is Yes.',
  },
  {
    id: 'logic_030',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 30: If X is 30, and Y is 31, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 30 < 31, the answer is Yes.',
  },
  {
    id: 'logic_031',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 31: If X is 31, and Y is 32, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 31 < 32, the answer is Yes.',
  },
  {
    id: 'logic_032',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 32: If X is 32, and Y is 33, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 32 < 33, the answer is Yes.',
  },
  {
    id: 'logic_033',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 33: If X is 33, and Y is 34, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 33 < 34, the answer is Yes.',
  },
  {
    id: 'logic_034',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 34: If X is 34, and Y is 35, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 34 < 35, the answer is Yes.',
  },
  {
    id: 'logic_035',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 35: If X is 35, and Y is 36, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 35 < 36, the answer is Yes.',
  },
  {
    id: 'logic_036',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 36: If X is 36, and Y is 37, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 36 < 37, the answer is Yes.',
  },
  {
    id: 'logic_037',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 37: If X is 37, and Y is 38, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 37 < 38, the answer is Yes.',
  },
  {
    id: 'logic_038',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 38: If X is 38, and Y is 39, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 38 < 39, the answer is Yes.',
  },
  {
    id: 'logic_039',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 39: If X is 39, and Y is 40, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 39 < 40, the answer is Yes.',
  },
  {
    id: 'logic_040',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 40: If X is 40, and Y is 41, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 40 < 41, the answer is Yes.',
  },
  {
    id: 'logic_041',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 41: If X is 41, and Y is 42, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 41 < 42, the answer is Yes.',
  },
  {
    id: 'logic_042',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 42: If X is 42, and Y is 43, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 42 < 43, the answer is Yes.',
  },
  {
    id: 'logic_043',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 43: If X is 43, and Y is 44, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 43 < 44, the answer is Yes.',
  },
  {
    id: 'logic_044',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 44: If X is 44, and Y is 45, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 44 < 45, the answer is Yes.',
  },
  {
    id: 'logic_045',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 45: If X is 45, and Y is 46, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 45 < 46, the answer is Yes.',
  },
  {
    id: 'logic_046',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 46: If X is 46, and Y is 47, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 46 < 47, the answer is Yes.',
  },
  {
    id: 'logic_047',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 47: If X is 47, and Y is 48, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 47 < 48, the answer is Yes.',
  },
  {
    id: 'logic_048',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'hard',
    question: 'Sample Logic Puzzle 48: If X is 48, and Y is 49, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 48 < 49, the answer is Yes.',
  },
  {
    id: 'logic_049',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'easy',
    question: 'Sample Logic Puzzle 49: If X is 49, and Y is 50, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 49 < 50, the answer is Yes.',
  },
  {
    id: 'logic_050',
    type: 'Logic',
    icon: '🎯',
    difficulty: 'medium',
    question: 'Sample Logic Puzzle 50: If X is 50, and Y is 51, what is X < Y?',
    options: ['Yes', 'No', 'Sometimes', 'Cannot determine'],
    correctAnswer: 0,
    explanation: 'Since 50 < 51, the answer is Yes.',
  }
];
