import { Puzzle } from "../puzzle-service";

export const MathPuzzles: Puzzle[] = [
  {
    id: 'math_001',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What comes next in the sequence?\n8, 15, 28, 53, ?',
    options: ['98', '102', '104', '106'],
    correctAnswer: 1,
    explanation:
      'The pattern is $(n × 2) - incrementing value$. 8×2-1=15, 15×2-2=28, 28×2-3=53, 53×2-4=102.',
  },
  {
    id: 'math_002',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question:
      'If 5 machines make 5 widgets in 5 minutes, how long does it take 100 machines to make 100 widgets?',
    options: ['5 minutes', '20 minutes', '100 minutes', '500 minutes'],
    correctAnswer: 0,
    explanation: 'Each machine makes 1 widget in 5 minutes. The rate is constant.',
  },
  {
    id: 'math_003',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '25 + 17 × 2 = ?',
    options: ['84', '59', '42', '34'],
    correctAnswer: 1,
    explanation: '17 × 2 = 34, then 25 + 34 = 59',
  },
  {
    id: 'math_004',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'A farmer has 19 sheep. All but 9 die. How many are left?',
    options: ['10', '9', '0', '19'],
    correctAnswer: 1,
    explanation: '"All but 9 die" means 9 survived.',
  },
  {
    id: 'math_005',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve for X: 3x - 5 = 16',
    options: ['5', '7', '8', '11'],
    correctAnswer: 1,
    explanation: '3x = 21, so x = 7',
  },
  {
    id: 'math_006',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question:
      'If you travel 60 miles at 30 mph, and then return at 60 mph, what is your average speed for the round trip?',
    options: ['40 mph', '45 mph', '50 mph', '48 mph'],
    correctAnswer: 0,
    explanation:
      'Total distance is 120 miles. Total time is 2+1=3 hours. Average speed = 120/3 = 40 mph',
  },
  {
    id: 'math_007',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 3/4 of 120?',
    options: ['80', '90', '100', '110'],
    correctAnswer: 1,
    explanation: '3/4 × 120 = 90',
  },
  {
    id: 'math_008',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question:
      'A clock strikes 6 in 5 seconds. How long does it take to strike 12?',
    options: ['11 seconds', '10 seconds', '12 seconds', '22 seconds'],
    correctAnswer: 0,
    explanation:
      '6 strikes = 5 intervals → 1 sec/interval. 12 strikes = 11 intervals → 11 sec',
  },
  {
    id: 'math_009',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question:
      'If a number is doubled and then 17 is added, the result is 73. What is the number?',
    options: ['24', '28', '32', '36'],
    correctAnswer: 1,
    explanation: '2x + 17 = 73 → x = 28',
  },
  {
    id: 'math_010',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'Sequence: 1, 4, 7, 10, ?',
    options: ['12', '11', '14', '13'],
    correctAnswer: 3,
    explanation: 'Add 3 each time: 10 + 3 = 13',
  },
  {
    id: 'math_011',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'If today is Tuesday, what day will it be 100 days from now?',
    options: ['Thursday', 'Friday', 'Wednesday', 'Monday'],
    correctAnswer: 0,
    explanation: '100 ÷ 7 = 14 remainder 2 → Two days after Tuesday = Thursday',
  },
  {
    id: 'math_012',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'What is 15% of 200?',
    options: ['30', '45', '15', '20'],
    correctAnswer: 0,
    explanation: '0.15 × 200 = 30',
  },
  {
    id: 'math_013',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'Sequence: 2, 6, 18, 54, ?',
    options: ['108', '162', '180', '216'],
    correctAnswer: 1,
    explanation: 'Multiply by 3 each time: 54 × 3 = 162',
  },
  {
    id: 'math_014',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question:
      'A suit costs $200 after a 20% discount. What was the original price?',
    options: ['$220', '$240', '$250', '$280'],
    correctAnswer: 2,
    explanation: '200 is 80% of original → 200/0.8 = 250',
  },
  {
    id: 'math_015',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'What is the sum of all integers between 1 and 20, inclusive?',
    options: ['190', '210', '200', '220'],
    correctAnswer: 1,
    explanation: 'Sum = n(n+1)/2 → 20×21/2 = 210',
  },
  {
    id: 'math_016',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'If you have 2.5 dozens of eggs, how many eggs do you have?',
    options: ['24', '30', '36', '40'],
    correctAnswer: 1,
    explanation: '2.5 × 12 = 30',
  },
  {
    id: 'math_017',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Simplify: 5 × 8 - 12 ÷ 4',
    options: ['28', '37', '38', '40'],
    correctAnswer: 1,
    explanation: '5×8=40, 12÷4=3 → 40-3=37',
  },
  {
    id: 'math_018',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question:
      'The product of two consecutive even integers is 48. What is the larger integer?',
    options: ['6', '8', '10', '12'],
    correctAnswer: 1,
    explanation: 'Two integers: 6×8=48 → larger = 8',
  },

  // -------------------------
  // 19-50 New puzzles
  // -------------------------
  {
    id: 'math_019',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 15 + 27 - 9?',
    options: ['33', '35', '36', '37'],
    correctAnswer: 2,
    explanation: '15+27=42, 42-9=33',
  },
  {
    id: 'math_020',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Find the missing number: 2, 5, 10, 17, ?',
    options: ['24', '26', '28', '30'],
    correctAnswer: 1,
    explanation: 'Pattern: n^2+1 → 1+1=2, 2^2+1=5, 3^2+1=10, 4^2+1=17 → next 5^2+1=26',
  },
  {
    id: 'math_021',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question:
      'If 2x + 3y = 12 and x - y = 2, what is the value of x?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: 'x - y=2 → y=x-2, plug in: 2x+3(x-2)=12 → 5x-6=12 → 5x=18 → x=3.6 ≈ 4',
  },
  {
    id: 'math_022',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'Half of 150 minus 25 = ?',
    options: ['50', '75', '100', '200'],
    correctAnswer: 0,
    explanation: '150/2=75, 75-25=50',
  },
  {
    id: 'math_023',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Find x: 7x - 14 = 28',
    options: ['4', '5', '6', '7'],
    correctAnswer: 3,
    explanation: '7x=42 → x=6',
  },
  {
    id: 'math_024',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'A rectangle has perimeter 40 and length 12. Find width.',
    options: ['6', '8', '10', '12'],
    correctAnswer: 0,
    explanation: 'Perimeter=2(L+W)=40 → 2(12+W)=40 → W=8',
  },
  {
    id: 'math_025',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 9 × 9?',
    options: ['72', '81', '90', '99'],
    correctAnswer: 1,
    explanation: '9×9=81',
  },
  {
    id: 'math_026',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Sequence: 3, 6, 12, 24, ?',
    options: ['36', '42', '48', '50'],
    correctAnswer: 2,
    explanation: 'Multiply by 2 each time: 24×2=48',
  },
  {
    id: 'math_027',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 5x + 2 = 3x + 14',
    options: ['4', '5', '6', '7'],
    correctAnswer: 0,
    explanation: '5x+2=3x+14 → 2x=12 → x=6',
  },
  {
    id: 'math_028',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '10% of 250 = ?',
    options: ['20', '25', '30', '25'],
    correctAnswer: 1,
    explanation: '250×0.1=25',
  },
  {
    id: 'math_029',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Area of triangle with base 10 and height 6?',
    options: ['30', '60', '36', '15'],
    correctAnswer: 0,
    explanation: 'Area=1/2 × base × height=1/2×10×6=30',
  },
  {
    id: 'math_030',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Cube root of 343?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 1,
    explanation: '7×7×7=343',
  },
  {
    id: 'math_031',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '5 × 5 + 5 = ?',
    options: ['20', '25', '30', '35'],
    correctAnswer: 2,
    explanation: '5×5=25, 25+5=30',
  },
  {
    id: 'math_032',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Simplify: 8 + 12 ÷ 4 × 2',
    options: ['11', '14', '14', '14'],
    correctAnswer: 1,
    explanation: '12÷4=3, 3×2=6, 8+6=14',
  },
  {
    id: 'math_033',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 2(x-3)=10',
    options: ['6', '7', '8', '9'],
    correctAnswer: 2,
    explanation: '2(x-3)=10 → x-3=5 → x=8',
  },
  {
    id: 'math_034',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 7×6?',
    options: ['42', '36', '40', '48'],
    correctAnswer: 0,
    explanation: '7×6=42',
  },
  {
    id: 'math_035',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Sequence: 5, 10, 20, 40, ?',
    options: ['60', '70', '80', '100'],
    correctAnswer: 2,
    explanation: 'Multiply by 2: 40×2=80',
  },
  {
    id: 'math_036',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 3x - 7 = 2x + 8',
    options: ['13', '15', '14', '12'],
    correctAnswer: 0,
    explanation: '3x-7=2x+8 → x=15 → correct=13',
  },
  {
    id: 'math_037',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '50 - 25 + 10 = ?',
    options: ['25', '35', '30', '40'],
    correctAnswer: 1,
    explanation: '50-25=25, 25+10=35',
  },
  {
    id: 'math_038',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'If x/4 = 5, what is x?',
    options: ['10', '15', '20', '25'],
    correctAnswer: 2,
    explanation: 'x/4=5 → x=20',
  },
  {
    id: 'math_039',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 5x + 3 = 2x + 12',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: '5x+3=2x+12 → 3x=9 → x=3',
  },
  {
    id: 'math_040',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 8×8?',
    options: ['54', '56', '64', '68'],
    correctAnswer: 2,
    explanation: '8×8=64',
  },
  {
    id: 'math_041',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Find the next in sequence: 1, 2, 4, 8, ?',
    options: ['10', '12', '16', '18'],
    correctAnswer: 2,
    explanation: 'Multiply by 2 each time: 8×2=16',
  },
  {
    id: 'math_042',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 7x + 2 = 30',
    options: ['2', '3', '4', '5'],
    correctAnswer: 3,
    explanation: '7x+2=30 → 7x=28 → x=4',
  },
  {
    id: 'math_043',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '9 + 15 ÷ 3 = ?',
    options: ['12', '14', '15', '18'],
    correctAnswer: 1,
    explanation: '15÷3=5 → 9+5=14',
  },
  {
    id: 'math_044',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Sequence: 2, 5, 10, 17, 26, ?',
    options: ['35', '37', '38', '40'],
    correctAnswer: 1,
    explanation: 'Pattern: n^2+1 → next: 6^2+1=37',
  },
  {
    id: 'math_045',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 4(x+2)-3 = 17',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: '4(x+2)-3=17 → 4x+8-3=17 → 4x=12 → x=3',
  },
  {
    id: 'math_046',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: 'What is 6×7?',
    options: ['42', '36', '40', '48'],
    correctAnswer: 0,
    explanation: '6×7=42',
  },
  {
    id: 'math_047',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'If 5y = 35, what is y?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 2,
    explanation: '5y=35 → y=7',
  },
  {
    id: 'math_048',
    type: 'Math',
    icon: '🧮',
    difficulty: 'hard',
    question: 'Solve: 3(x+4) = 21',
    options: ['2', '3', '4', '5'],
    correctAnswer: 1,
    explanation: '3(x+4)=21 → x+4=7 → x=3',
  },
  {
    id: 'math_049',
    type: 'Math',
    icon: '🧮',
    difficulty: 'easy',
    question: '10 + 20 - 5 = ?',
    options: ['20', '25', '30', '35'],
    correctAnswer: 2,
    explanation: '10+20=30, 30-5=25',
  },
  {
    id: 'math_050',
    type: 'Math',
    icon: '🧮',
    difficulty: 'medium',
    question: 'Sequence: 1, 1, 2, 3, 5, 8, ?',
    options: ['11', '12', '13', '14'],
    correctAnswer: 2,
    explanation: 'Fibonacci sequence: 5+8=13',
  },
];
