import { Puzzle } from '../puzzle-service';

export const MemoryPuzzles: Puzzle[] = [
  {
    id: 'memory_001',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: 7 - 3 - 9 - 1 - 5\nWhat is the 3rd number?',
    options: ['3', '9', '1', '5'],
    correctAnswer: 1,
  },
  {
    id: 'memory_002',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: DOG, CAT, BIRD, FISH\nWhich was 2nd?',
    options: ['DOG', 'CAT', 'BIRD', 'FISH'],
    correctAnswer: 1,
  },
  {
    id: 'memory_003',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: Red, Blue, Green\nWhat was the first color?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correctAnswer: 0,
  },
  {
    id: 'memory_004',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: 4 - 8 - 2 - 6\nWhat was the last number?',
    options: ['4', '8', '2', '6'],
    correctAnswer: 3,
  },
  {
    id: 'memory_005',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: Sun, Moon, Star\nWhich came 2nd?',
    options: ['Sun', 'Moon', 'Star', 'Sky'],
    correctAnswer: 1,
  },
  {
    id: 'memory_006',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: APPLE, TIGER, CLOUD, PIANO\nWhich word was 2nd?',
    options: ['APPLE', 'TIGER', 'CLOUD', 'PIANO'],
    correctAnswer: 1,
  },
  {
    id: 'memory_007',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question:
      'Memorize: Square, Circle, Triangle, Star\nWhich shape was first?',
    options: ['Square', 'Circle', 'Triangle', 'Star'],
    correctAnswer: 0,
  },
  {
    id: 'memory_008',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: K, L, M, N\nWhich letter was before N?',
    options: ['K', 'L', 'M', 'O'],
    correctAnswer: 2,
  },
  {
    id: 'memory_009',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: Book, Chair, Lamp, Desk\nWhich was 3rd?',
    options: ['Book', 'Chair', 'Lamp', 'Desk'],
    correctAnswer: 2,
  },
  {
    id: 'memory_010',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: LIBRARY\nWhat was the 3rd letter?',
    options: ['B', 'R', 'A', 'Y'],
    correctAnswer: 0,
  },
  {
    id: 'memory_011',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: North, East, South, West\nWhich direction was 3rd?',
    options: ['North', 'East', 'South', 'West'],
    correctAnswer: 2,
  },
  {
    id: 'memory_012',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question:
      'Memorize: Fork, Spoon, Plate, Knife, Glass\nWhich was in middle?',
    options: ['Fork', 'Spoon', 'Plate', 'Knife'],
    correctAnswer: 2,
  },
  {
    id: 'memory_013',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 10, 50, 90\nWhat was middle number?',
    options: ['10', '50', '90', 'None'],
    correctAnswer: 1,
  },
  {
    id: 'memory_014',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 1945\nSum of digits?',
    options: ['15', '19', '17', '18'],
    correctAnswer: 1,
    explanation: '1+9+4+5=19',
  },
  {
    id: 'memory_015',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 🔵 🔴 🟢 🟡 🔵\nWhich color appeared twice?',
    options: ['Blue', 'Red', 'Green', 'Yellow'],
    correctAnswer: 0,
  },
  {
    id: 'memory_016',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 93175\nDifference first-last digit?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
    explanation: '9-5=4',
  },
  {
    id: 'memory_017',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: R-H-P-T-J\nWhich letter after H?',
    options: ['R', 'P', 'T', 'J'],
    correctAnswer: 1,
  },
  {
    id: 'memory_018',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Pattern: △, □, △, □, △, ?\nWhich shape comes next?',
    options: ['△', '□', '○', '◇'],
    correctAnswer: 1,
  },
  {
    id: 'memory_019',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: 5-2-8-7-1\nWhat is 4th number?',
    options: ['5', '2', '7', '1'],
    correctAnswer: 2,
  },
  {
    id: 'memory_020',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: Mango, Banana, Apple, Orange\nWhich was 2nd?',
    options: ['Mango', 'Banana', 'Apple', 'Orange'],
    correctAnswer: 1,
  },
  {
    id: 'memory_021',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: 1,4,7,10\nNext number?',
    options: ['12', '11', '14', '13'],
    correctAnswer: 3,
  },
  {
    id: 'memory_022',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'easy',
    question: 'Memorize: Lion, Tiger, Bear, Fox\nWhich was 3rd?',
    options: ['Lion', 'Tiger', 'Bear', 'Fox'],
    correctAnswer: 2,
  },
  {
    id: 'memory_023',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: X,Y,Z,A,B\nWhat was 3rd?',
    options: ['X', 'Y', 'Z', 'A'],
    correctAnswer: 2,
  },
  {
    id: 'memory_024',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 2,4,6,8,10\nSum first+last?',
    options: ['12', '14', '16', '18'],
    correctAnswer: 1,
  },
  {
    id: 'memory_025',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: Chair, Pen, Book, Table\nWhich 2nd?',
    options: ['Chair', 'Pen', 'Book', 'Table'],
    correctAnswer: 1,
  },
  {
    id: 'memory_026',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 3,7,1,9,4\nSum 1st+3rd?',
    options: ['6', '10', '7', '8'],
    correctAnswer: 3,
  },
  {
    id: 'memory_027',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: Blue, Green, Red, Yellow\nWhich color last?',
    options: ['Blue', 'Green', 'Red', 'Yellow'],
    correctAnswer: 3,
  },
  {
    id: 'memory_028',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 8,4,6,2,7\nWhich 2nd?',
    options: ['8', '4', '6', '2'],
    correctAnswer: 1,
  },
  {
    id: 'memory_029',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: 12,9,15,7\nSum 1st+last?',
    options: ['19', '20', '18', '21'],
    correctAnswer: 0,
  },
  {
    id: 'memory_030',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'medium',
    question: 'Memorize: Pen, Notebook, Eraser, Pencil\nWhich 2nd?',
    options: ['Pen', 'Notebook', 'Eraser', 'Pencil'],
    correctAnswer: 1,
  },
  {
    id: 'memory_031',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 482019\nSum 1st+last?',
    options: ['11', '12', '13', '14'],
    correctAnswer: 2,
    explanation: '4+9=13',
  },
  {
    id: 'memory_032',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Pattern: Triangle, Square, Star, Square\nWhich appeared twice?',
    options: ['Triangle', 'Star', 'Square', 'Circle'],
    correctAnswer: 2,
  },
  {
    id: 'memory_033',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: R-H-P-T-J\nWhich letter 4th?',
    options: ['R', 'H', 'P', 'T'],
    correctAnswer: 3,
  },
  {
    id: 'memory_034',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 93175\nDifference 1st-last?',
    options: ['2', '3', '4', '5'],
    correctAnswer: 2,
  },
  {
    id: 'memory_035',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 🔵 🔴 🟢 🟡 🔵\nWhich color repeated?',
    options: ['Blue', 'Red', 'Green', 'Yellow'],
    correctAnswer: 0,
  },
  {
    id: 'memory_036',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 246813\nSum 2nd+5th?',
    options: ['10', '12', '14', '16'],
    correctAnswer: 2,
  },
  {
    id: 'memory_037',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Pattern: ◇, △, ◇, △, ?\nNext?',
    options: ['◇', '△', '□', '○'],
    correctAnswer: 1,
  },
  {
    id: 'memory_038',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: C-B-A-D-E\n3rd letter?',
    options: ['C', 'B', 'A', 'D'],
    correctAnswer: 2,
  },
  {
    id: 'memory_039',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 7-2-9-4-1\nSum 2nd+4th?',
    options: ['6', '7', '8', '9'],
    correctAnswer: 3,
  },
  {
    id: 'memory_040',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: Sun, Star, Moon, Cloud\n2nd?',
    options: ['Sun', 'Star', 'Moon', 'Cloud'],
    correctAnswer: 1,
  },
  {
    id: 'memory_041',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 5,1,3,7,9\nLast digit?',
    options: ['5', '1', '3', '9'],
    correctAnswer: 3,
  },
  {
    id: 'memory_042',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: Red, Blue, Green, Yellow, Orange\n3rd?',
    options: ['Red', 'Blue', 'Green', 'Yellow'],
    correctAnswer: 2,
  },
  {
    id: 'memory_043',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 12,5,8,3,7\nSum 1st+last?',
    options: ['19', '18', '20', '21'],
    correctAnswer: 0,
  },
  {
    id: 'memory_044',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: Apple, Banana, Mango, Kiwi, Orange\n4th?',
    options: ['Apple', 'Banana', 'Mango', 'Kiwi'],
    correctAnswer: 3,
  },
  {
    id: 'memory_045',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 🔺 🔵 🔺 🔵 🔺\nWhich repeated?',
    options: ['Triangle', 'Circle', 'Star', 'Square'],
    correctAnswer: 0,
  },
  {
    id: 'memory_046',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 5,3,8,2,7\nSum middle?',
    options: ['8', '10', '12', '7'],
    correctAnswer: 1,
  },
  {
    id: 'memory_047',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: Cat, Dog, Rat, Bat, Fox\n3rd?',
    options: ['Cat', 'Dog', 'Rat', 'Bat'],
    correctAnswer: 2,
  },
  {
    id: 'memory_048',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 1,3,5,7,9\nSum first+last?',
    options: ['10', '11', '12', '13'],
    correctAnswer: 2,
  },
  {
    id: 'memory_049',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: Blue, Red, Green, Yellow, Orange\nLast color?',
    options: ['Blue', 'Red', 'Green', 'Orange'],
    correctAnswer: 3,
  },
  {
    id: 'memory_050',
    type: 'Memory',
    icon: '🧠',
    difficulty: 'hard',
    question: 'Memorize: 6-2-8-3-9\nSum 2nd+4th?',
    options: ['5', '6', '7', '8'],
    correctAnswer: 3,
  },
];
