import { Puzzle } from '../puzzle-service';

export const PatternPuzzles: Puzzle[] = [
  {
    id: 'pattern_001',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'easy',
    question: 'Find the next number: 2, 4, 6, 8, ?',
    options: ['9', '10', '12', '14'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_002',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'easy',
    question: 'Find the next number: 1, 3, 5, 7, ?',
    options: ['9', '8', '10', '11'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_003',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'easy',
    question: 'Find the next number: 5, 10, 15, 20, ?',
    options: ['25', '24', '30', '22'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_004',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'easy',
    question: 'Find the next number: 0, 1, 1, 2, 3, ?',
    options: ['4', '5', '6', '3'],
    correctAnswer: 0,
    explanation: 'Fibonacci sequence',
  },
  {
    id: 'pattern_005',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'easy',
    question: 'Find the missing number: 2, 4, 8, 16, ?',
    options: ['24', '32', '30', '20'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_006',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 3, 6, 12, 24, ?',
    options: ['30', '36', '48', '50'],
    correctAnswer: 2,
  },
  {
    id: 'pattern_007',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 7, 14, 28, 56, ?',
    options: ['70', '112', '100', '120'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_008',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 1, 4, 9, 16, ?',
    options: ['25', '20', '21', '24'],
    correctAnswer: 0,
    explanation: 'Perfect squares',
  },
  {
    id: 'pattern_009',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 2, 6, 12, 20, ?',
    options: ['28', '30', '32', '36'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_010',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 1, 2, 6, 24, ?',
    options: ['96', '120', '120', '120'],
    correctAnswer: 1,
    explanation: 'Factorial pattern',
  },
  {
    id: 'pattern_011',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 5, 11, 23, 47, ?',
    options: ['90', '95', '93', '94'],
    correctAnswer: 3,
  },
  {
    id: 'pattern_012',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 2, 3, 5, 7, 11, ?',
    options: ['13', '12', '15', '14'],
    correctAnswer: 0,
    explanation: 'Prime numbers',
  },
  {
    id: 'pattern_013',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 1, 2, 4, 8, 16, ?',
    options: ['32', '30', '28', '34'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_014',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 10, 20, 40, 80, ?',
    options: ['120', '160', '140', '180'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_015',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 2, 6, 24, 120, ?',
    options: ['600', '720', '720', '720'],
    correctAnswer: 1,
    explanation: 'Factorial pattern',
  },
  {
    id: 'pattern_016',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 2, 12, 30, 56, ?',
    options: ['90', '110', '92', '96'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_017',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 1, 2, 6, 24, 120, ?',
    options: ['720', '720', '840', '600'],
    correctAnswer: 0,
    explanation: 'Factorials',
  },
  {
    id: 'pattern_018',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 2, 5, 10, 17, 26, ?',
    options: ['35', '36', '34', '38'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_019',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 3, 9, 27, 81, ?',
    options: ['162', '243', '210', '220'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_020',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 8, 27, 64, ?',
    options: ['125', '100', '150', '120'],
    correctAnswer: 0,
    explanation: 'Cubes of numbers',
  },
  {
    id: 'pattern_021',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 4, 10, 18, 28, ?',
    options: ['36', '40', '38', '42'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_022',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 3, 9, 27, ?',
    options: ['81', '90', '75', '100'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_023',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 2, 4, 8, 32, ?',
    options: ['64', '128', '96', '100'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_024',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 0, 1, 3, 6, 10, ?',
    options: ['14', '15', '16', '13'],
    correctAnswer: 1,
    explanation: 'Triangular numbers',
  },
  {
    id: 'pattern_025',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 1, 4, 9, 16, ?',
    options: ['25', '20', '21', '22'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_026',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 1, 2, 4, 8, 16, ?',
    options: ['32', '30', '28', '34'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_027',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 3, 6, 12, 24, ?',
    options: ['48', '50', '46', '52'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_028',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the next number: 5, 11, 17, 23, ?',
    options: ['28', '29', '30', '31'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_029',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'medium',
    question: 'Find the missing number: 2, 6, 12, 20, ?',
    options: ['30', '28', '32', '26'],
    correctAnswer: 1,
  },
  {
    id: 'pattern_030',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 1, 2, 5, 14, ?',
    options: ['42', '40', '44', '45'],
    correctAnswer: 0,
    explanation: 'Catalan numbers',
  },
  {
    id: 'pattern_031',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 2, 6, 20, 70, ?',
    options: ['252', '250', '260', '240'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_032',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 4, 10, 20, 35, ?',
    options: ['56', '55', '60', '50'],
    correctAnswer: 0,
    explanation: 'Triangular numbers',
  },
  {
    id: 'pattern_033',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 5, 14, 30, ?',
    options: ['55', '54', '56', '50'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_034',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 2, 6, 12, 20, 30, ?',
    options: ['42', '40', '44', '38'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_035',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 2, 6, 24, ?',
    options: ['120', '100', '110', '130'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_036',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 3, 5, 9, 17, 33, ?',
    options: ['65', '63', '67', '60'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_037',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 3, 6, 10, 15, ?',
    options: ['21', '20', '22', '23'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_038',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 2, 4, 8, 16, 32, ?',
    options: ['64', '60', '66', '62'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_039',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 4, 10, 20, 35, ?',
    options: ['56', '55', '60', '50'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_040',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 2, 3, 5, 8, 12, ?',
    options: ['17', '18', '16', '15'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_041',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 2, 4, 7, 11, ?',
    options: ['16', '15', '17', '14'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_042',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 2, 6, 24, 120, ?',
    options: ['720', '700', '750', '710'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_043',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 3, 6, 12, 24, 48, ?',
    options: ['96', '100', '94', '98'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_044',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 3, 9, 27, 81, ?',
    options: ['243', '240', '250', '245'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_045',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 2, 5, 10, 17, 26, ?',
    options: ['37', '36', '35', '38'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_046',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 4, 7, 11, 16, 22, ?',
    options: ['29', '28', '30', '27'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_047',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 1, 2, 5, 10, 17, ?',
    options: ['26', '25', '27', '24'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_048',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 8, 27, 64, ?',
    options: ['125', '120', '130', '135'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_049',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the missing number: 2, 6, 12, 20, 30, ?',
    options: ['42', '40', '44', '38'],
    correctAnswer: 0,
  },
  {
    id: 'pattern_050',
    type: 'Pattern',
    icon: '🔷',
    difficulty: 'hard',
    question: 'Find the next number: 1, 3, 6, 10, 15, ?',
    options: ['21', '20', '22', '23'],
    correctAnswer: 0,
  },
];
