import { Puzzle } from '../puzzle-service';

export const RiddlePuzzles: Puzzle[] = [
  {
    id: 'riddle_001',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'easy',
    question: 'I speak without a mouth and hear without ears. What am I?',
    options: ['Echo', 'Shadow', 'Wind', 'Thought'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_002',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'easy',
    question: 'I have keys but no locks. What am I?',
    options: ['Piano', 'Map', 'Door', 'Clock'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_003',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'easy',
    question: 'What has hands but cannot clap?',
    options: ['Clock', 'Tree', 'Robot', 'Chair'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_004',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'easy',
    question: 'What can travel around the world while staying in a corner?',
    options: ['Stamp', 'Sun', 'Bird', 'Moon'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_005',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'easy',
    question: 'What has a heart that doesn’t beat?',
    options: ['Artichoke', 'Stone', 'Tree', 'River'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_006',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'The more of this there is, the less you see. What is it?',
    options: ['Darkness', 'Fog', 'Water', 'Sand'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_007',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'I’m tall when I’m young and short when I’m old. What am I?',
    options: ['Candle', 'Tree', 'Pencil', 'Human'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_008',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'What has an eye but cannot see?',
    options: ['Needle', 'Potato', 'Storm', 'Camera'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_009',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'What gets wetter as it dries?',
    options: ['Towel', 'Sponge', 'Soap', 'Rain'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_010',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'What belongs to you but is used more by others?',
    options: ['Your name', 'Your phone', 'Your wallet', 'Your shoes'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_011',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'I’m always in front of you but can’t be seen. What am I?',
    options: ['Future', 'Air', 'Shadow', 'Time'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_012',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'What can be broken but never held?',
    options: ['Promise', 'Glass', 'Heart', 'Egg'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_013',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question:
      'I’m found in socks, scarves, and mittens; sometimes in the paws of playful kittens. What am I?',
    options: ['Thread', 'Cotton', 'Wool', 'Yarn'],
    correctAnswer: 3,
  },
  {
    id: 'riddle_014',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'What runs, but never walks, has a mouth but never talks?',
    options: ['River', 'Clock', 'Wind', 'Train'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_015',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'medium',
    question: 'I can fill a room but take up no space. What am I?',
    options: ['Light', 'Air', 'Sound', 'Shadow'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_016',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I am always hungry, I must always be fed. The finger I touch will soon turn red. What am I?',
    options: ['Fire', 'Acid', 'Rust', 'Time'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_017',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'The more you take, the more you leave behind. What am I?',
    options: ['Footsteps', 'Time', 'Memories', 'Shadows'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_018',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'What has cities, but no houses; forests, but no trees; and water, but no fish?',
    options: ['Map', 'Globe', 'Atlas', 'Imagination'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_019',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I’m not alive, but I grow; I don’t have lungs, but I need air; I don’t have a mouth, and yet water kills me. What am I?',
    options: ['Fire', 'Cloud', 'Wind', 'Stone'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_020',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'What comes once in a minute, twice in a moment, but never in a thousand years?',
    options: ['The letter M', 'Time', 'Moon', 'Sun'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_021',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I have branches, but no fruit, trunk, or leaves. What am I?',
    options: ['Bank', 'River', 'Tree', 'Library'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_022',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I’m light as a feather, yet the strongest man cannot hold me for long. What am I?',
    options: ['Breath', 'Air', 'Time', 'Shadow'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_023',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'The more you take away from me, the bigger I get. What am I?',
    options: ['Hole', 'Cave', 'Darkness', 'Sand'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_024',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I’m always moving, but I have no legs. You can see me but never touch me. What am I?',
    options: ['Time', 'Wind', 'Shadow', 'River'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_025',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I have a neck but no head, two arms but no hands. What am I?',
    options: ['Shirt', 'Clock', 'Bottle', 'Tree'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_026',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I have lakes with no water, mountains with no stone, and cities with no buildings. What am I?',
    options: ['Map', 'Globe', 'Puzzle', 'Painting'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_027',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'What begins with T, ends with T, and has T in it?',
    options: ['Teapot', 'Tent', 'Toast', 'Ticket'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_028',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I’m often running, but I never move. What am I?',
    options: ['Water', 'Clock', 'Time', 'River'],
    correctAnswer: 1,
  },
  {
    id: 'riddle_029',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I’m always ahead, never behind. I can’t be stopped, and I am constant. What am I?',
    options: ['Time', 'Clock', 'Wind', 'Shadow'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_030',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I am full of holes but still holds water. What am I?',
    options: ['Sponge', 'Net', 'Bucket', 'Strainer'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_031',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I have one eye, but cannot see. What am I?',
    options: ['Needle', 'Storm', 'Potato', 'Button'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_032',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I shrink smaller every time I take a bath. What am I?',
    options: ['Soap', 'Ice', 'Candle', 'Sponge'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_033',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. What am I?',
    options: ['Cloud', 'Wind', 'Time', 'Shadow'],
    correctAnswer: 3,
  },
  {
    id: 'riddle_034',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I am not alive, but I can die if you put me in water. What am I?',
    options: ['Fire', 'Ice', 'Wind', 'Metal'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_035',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I can be cracked, made, told, and played. What am I?',
    options: ['Joke', 'Egg', 'Puzzle', 'Code'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_036',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I have a head, a tail, but no body. What am I?',
    options: ['Coin', 'Snake', 'Comet', 'Arrow'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_037',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I am always coming, but never arrive. What am I?',
    options: ['Tomorrow', 'Time', 'Shadow', 'Rain'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_038',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I have roots that nobody sees, I am taller than trees. What am I?',
    options: ['Mountain', 'Plant', 'Tree', 'Rock'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_039',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I go in dry and come out wet. The longer I stay in, the stronger I get. What am I?',
    options: ['Tea bag', 'Sponge', 'Soap', 'Cloth'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_040',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I am invisible, yet you can feel me. I am everywhere, yet cannot be caught. What am I?',
    options: ['Air', 'Time', 'Wind', 'Shadow'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_041',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I am taken from a mine, and shut in a wooden case, from which I am never released, and yet I am used by almost every person. What am I?',
    options: ['Pencil lead', 'Gold', 'Coal', 'Diamond'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_042',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I fly without wings, I cry without eyes, and the darkness follows me. What am I?',
    options: ['Cloud', 'Shadow', 'Wind', 'Time'],
    correctAnswer: 1,
  },
  {
    id: 'riddle_043',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I have no voice, yet I speak to you. I tell you all I know. What am I?',
    options: ['Book', 'Radio', 'Phone', 'Letter'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_044',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I run but never walk, I have a bed but never sleep. What am I?',
    options: ['River', 'Clock', 'Wind', 'Time'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_045',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'I’m tall when young, and short when old. What am I?',
    options: ['Candle', 'Pencil', 'Tree', 'Person'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_046',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I can be cracked, I can be made, I can be told, I can be played. What am I?',
    options: ['Joke', 'Egg', 'Puzzle', 'Story'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_047',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I have keys but open no locks. I have space but no room. You can enter, but can’t go outside. What am I?',
    options: ['Keyboard', 'Piano', 'Map', 'Safe'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_048',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I’m light as a feather, yet the strongest person cannot hold me for long. What am I?',
    options: ['Breath', 'Air', 'Cloud', 'Time'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_049',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question:
      'I am always moving, but I have no legs. I am everywhere, yet cannot be seen. What am I?',
    options: ['Time', 'Wind', 'Shadow', 'Air'],
    correctAnswer: 0,
  },
  {
    id: 'riddle_050',
    type: 'Riddle',
    icon: '🧩',
    difficulty: 'hard',
    question: 'The more you take away from me, the bigger I get. What am I?',
    options: ['Hole', 'Cave', 'Sand', 'Darkness'],
    correctAnswer: 0,
  },
];
